### ISSUE TITLE
error: invalid MessageComponentType

### ISSUE THREAD

**Issue by MrHomeless32** [discord-buttons/discord-buttons#127]
[my bot]/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:28
                throw new SyntaxError('INVALID_TYPE: Invalid MessageComponentType');
                ^

SyntaxError: INVALID_TYPE: Invalid MessageComponentType
    at Function.create ([my bot]/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:28:23)
    at [my bot]/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:77
    at Array.map (<anonymous>)
    at MessageActionRow.setup ([my bot]/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:47)
    at new MessageActionRow ([my bot]/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:8:14)
    at Function.create ([my bot]/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:19:29)
    at [my bot]/node_modules/discord-buttons/src/v12/Classes/Message.js:10:81
    at Array.map (<anonymous>)
    at ExtendedMessage._patch ([my bot]/node_modul
    
    ------------------------------------------------------------
    I'm not sure what causes this, because I don't use the package myself, I used other packages that needed discord buttons as a requirement and they work normally with no issues.
also I'm using discord js v12, didn't update yet

**Comment by DollnKey** [comment]
You must place the components one by one, inside a **MessageActionRow**! Like this: `.addComponent(<variable>)`.
And don't use `.addComponents(<variables>)`

**Comment by LoneWolf6969** [comment]
This issue has been resolved in version ```4.0.0``` . Updating should fix it!

**Comment by Assassin-1234** [comment]
this usually occurs when you try to send a button in the component message option. Action rows have type `1` and buttons have type `2`. You cannot send type 2 instead of 1, therefore the error

**Comment by alperb** [comment]
This issue can be closed i think since this problem is resolved

> This issue has been resolved in version `4.0.0` . Updating should fix it! Make sure the package you are using is also up-to-date.
