### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by NotTimIsReal** [discord-buttons/discord-buttons#172]
I get this error when starting my bot,
```
/home/ubuntu/bbarevamp/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:9
class sendAPICallback extends dAPIMessage {
                              ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/ubuntu/bbarevamp/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:9:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/ubuntu/bbarevamp/node_modules/discord-buttons/src/v12/Classes/WebhookClient.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/ubuntu/bbarevamp/node_modules/discord-buttons/src/v12/Classes/MessageComponent.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

I have updated Discord.js to V13 and I have also updates discord-buttons

**Comment by LoneWolf6969** [comment]
Discord-buttons does not have support for discord.js v13. We would recommend the djs inbuild buttons

**Comment by NotTimIsReal** [comment]
> Discord-buttons does not have support for discord.js v13. We would recommend the djs inbuild buttons

Is that in the discord.js library or is it a different module?

**Comment by LoneWolf6969** [comment]
In Discord.js library

**Comment by NotTimIsReal** [comment]
Because some of my modules required this package.....
