### ISSUE TITLE
Invalid MessageComponentType

### ISSUE THREAD

**Issue by LucasPanais** [discord-buttons/discord-buttons#174]
SyntaxError: INVALID_TYPE: Invalid MessageComponentType
    at Function.create (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:28:23)
    at /home/pi/panais/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:77
    at Array.map (<anonymous>)
    at MessageActionRow.setup (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:18:47)
    at new MessageActionRow (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/MessageActionRow.js:8:14)
    at Function.create (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/interfaces/BaseMessageComponent.js:19:29)
    at /home/pi/panais/node_modules/discord-buttons/src/v12/Classes/Message.js:10:81
    at Array.map (<anonymous>)
    at ExtendedMessage._patch (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/Message.js:10:51)
    at new Message (/home/pi/panais/node_modules/discord.js/src/structures/Message.js:44:20)
    at new ExtendedMessage (/home/pi/panais/node_modules/discord-buttons/src/v12/Classes/Message.js:6:1)
    at MessageManager.add (/home/pi/panais/node_modules/discord.js/src/managers/BaseManager.js:49:32)
    at MessageManager.add (/home/pi/panais/node_modules/discord.js/src/managers/MessageManager.js:30:18)
    at MessageCreateAction.handle (/home/pi/panais/node_modules/discord.js/src/client/actions/MessageCreate.js:13:40)
    at Object.module.exports [as MESSAGE_CREATE] (/home/pi/panais/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/pi/panais/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

**Comment by LoneWolf6969** [comment]
Make sure you are using version 4.0.0

**Comment by LucasPanais** [comment]
okay nice
